/** Studio default parameters from liquid-glass-studio Controls.tsx */
export const defaults = {
  refThickness: 20,
  refFactor: 1.4,
  refDispersion: 7,
  refFresnelRange: 30,
  refFresnelHardness: 20,
  refFresnelFactor: 20,
  glareRange: 30,
  glareHardness: 20,
  glareFactor: 90,
  glareConvergence: 50,
  glareOppositeFactor: 80,
  glareAngle: -45,
  blurRadius: 12,
  blurEdge: true,
  tint: { r: 255, g: 255, b: 255, a: 0 },
  shadowExpand: 28,
  shadowFactor: 26,
  shadowPosition: { x: 0, y: -12 },
  bgType: 3,
  shapeWidth: 200,
  shapeHeight: 200,
  shapeRadius: 100,
  shapeRoundness: 2,
  mergeRate: 0.05,
  showShape1: false,
  step: 9,
} as const;
